### ISSUE TITLE
Make Error "undeclared identifier 'MAP_POPULATE'"

### ISSUE THREAD

**Issue by rpaudel42** [sbustreamspot/sbustreamspot-core#36]
Can you help me how to fix this erro
<img width="611" alt="Screen Shot 2019-07-09 at 6 16 43 PM" src="https://user-images.githubusercontent.com/25356508/60929169-dc281b00-a275-11e9-8aa3-89e0a3c0ec51.png">

**Comment by emaadmanzoor** [comment]
Are you running this on Linux? I have not tested this on any other platform. It appears you don't have some of the required headers that define `MAP_POPULATE`.

**Comment by rpaudel42** [comment]
Thank you for the prompt reply.
I had a compilation error because I was running in MacOS. 
I tried in Linux and it runs perfectly. Thank you.
