### ISSUE TITLE
How to interpret the output and get accuracy/precison/F-Score

### ISSUE THREAD

**Issue by yemai666** [sbustreamspot/sbustreamspot-core#37]
![image](https://user-images.githubusercontent.com/48974017/227763962-309cd291-cd5c-4f5b-860b-532432b8efe3.png)
 I'd like to do a comparison test to get accuracy and precison,but the output like this ,whould you  please tell me how to interpret the output data ?How do you get a label that predicts whether this graph is benign or attack?

Thanks!

**Comment by emaadmanzoor** [comment]
Hello!

Streamspot calculates an anomaly score for each graph on the arrival of each new edge. Each new edge arrival is called an "iteration".

The anomaly scores for each graph are the numbers right after "Iterations 2303", where the score is -2 if the graph has not yet been seen (no edges for this graph have arrived). Higher scores imply more anomalous graphs. The second line of numbers are assignments of graphs to clusters: you can ignore these.

To get a predicted label, you will have to threshold the score (eg. let all graphs with score > 0.8 be flagged as attack, and the other graphs be considered benign). Once you have these predicted labels, you can compare with the true labels to calculate metrics like precision and accuracy.

Does this help?

**Comment by yemai666** [comment]
Thank you very much for your answer, I understand it.
 I have one more question, I want to do a comparison experiment, and I want to use 60% data for training instead of 75%. Is there any code that can automatically generate Bootstrap clusters according to my requirements?
Can the *.cl file generated in sbustreamspot-train be provided as the Bootstrapclusters.txt in sbustreamspot-core?
but why the first line in *.cl have 4 parameters but in Bootstrapclusters.txt has only 2 parameters?

**Comment by emaadmanzoor** [comment]
You can use the code in sbustreamspot-train, but this was developed for a subsequent project, and the code will need to be slightly modified. This is why the *.cl has 4 parameters.

**Comment by yemai666** [comment]
Thank you for your patient reply, which has helped me a lot！
